/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.common.base.Joiner;
import com.google.gson.Gson;

public class App {
    public String getGreeting() {
        String[] words = {"Hello", "World"};
        String message = Joiner.on(", ").join(words);
        System.out.println(message);

        System.out.println("Hello World!");
        Gson gson = new Gson();

        return message;
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

        Person person = new Person("Lena", "Davydova", 25);
        System.out.println(person.equals(new Person("Irina", "Vasileva", 35)));
        System.out.println(person.hashCode());
        System.out.println(person);
    }
}
